#!/bin/bash
# REV04: Mon Feb 26 21:37:53 WIB 2018
# START: Mon Sep  4 16:42:56 WIB 2017

# R: Does "ZA-thisfile.txt" exists? Run "bash a04-does-it-exist"

# Copyright (C)2017-2018 Rahmat M. Samik-Ibrahim
# http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

PREFIX="^#.R:"
RESULT=`grep $PREFIX $0`
clear
if [[ $RESULT ]] ; then
   printf "\n[%11s]: %s\n" "`cut -c 1-11 <<< $0`" "$RESULT"
fi
echo ""; 

FILE="ZA-thisfile.txt"
[ -f $FILE ] && {
  echo "$FILE EXISTS!"
}
[ -f $FILE ] || {
  echo "$FILE does not EXISTS!"
}
echo ""

exit

